name: expense_tracker
description: "A Flutter expense tracker app with Firebase and Stripe integration."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  fl_chart: ^0.66.0
  provider: ^6.1.5

  firebase_core: ^3.10.0
  firebase_auth: ^5.2.0
  cloud_firestore: ^5.0.0

  flutter_stripe: ^9.0.0
  http: ^1.1.0
  flutter_dotenv: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  google_fonts: ^6.1.0
  animate_do: ^3.3.4
  shared_preferences: ^2.2.2
  excel: ^4.0.2
  path_provider: ^2.1.2
  permission_handler: ^11.3.0

flutter:
  uses-material-design: true
  assets:
    - .env
